server:
  port: 8081
xxl:
  job:
    accessToken: ''
    admin:
#      addresses: http://106.53.248.242:8888/xxl-job-admin
      addresses: http://192.168.1.201:8888/xxl-job-admin
    executor:
      address: ''
      appname: xxl-job-test
      ip: '192.168.2.217'
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
      port: 9999
